// Generated by "runko project create" (build_engine: vite, docs/design.md
// §14.5.5) and nested under frontend/. Vite is a territory scaffold, not a
// build-graph engine (§14.5.4) — this project rides the declared affected
// floor; there is no capability_config.build binding to keep in sync.
import { defineConfig } from "vite";

export default defineConfig({
  server: {
    port: 5173,
    proxy: {
      // REST API from openapi.yaml (local server)
      "/api": "http://127.0.0.1:8787",
      "/healthz": "http://127.0.0.1:8787",
    },
  },
});
