schema: project/v1
name: hello
type: library
language: go
owners:
    - user:admin
capabilities:
    - build
capability_config:
    build:
        engine: bazel
        target_patterns:
            - //hello/...
